DEFAULT_TIMEOUT = 10
SITEMAP_TIMEOUT = 10
ROBOTS_TIMEOUT = 10
MAX_SITEMAP_DEPTH = 2
MAX_URLS_PER_SITEMAP = 10000

# DataForSEO credentials
DATAFORSEO_LOGIN = 'admin@superlewis.com'
DATAFORSEO_PASSWORD = 'DATAFORSEO_PASSWORD', 'ab0d272e760b2521'

# Google Custom Search API credentials
GOOGLE_API_KEY = 'AIzaSyCRVOxLnLyPhUHTC7Kptdfqoc-XkmBim7Q'
GOOGLE_CSE_ID = '169645a78955f41cb'
